name       : gperf
version    : '3.1'
release    : 5
source     :
    - https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz : 588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2
homepage   : https://www.gnu.org/software/gperf/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Gperf generates a perfect hash function from a key set
description: |
    Gperf generates a perfect hash function from a key set.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
