name       : gperf
version    : '3.1'
release    : 4
source     :
    - https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz : 588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2
homepage   : http://www.gnu.org
license    :
    - GPL-3.0
summary    : Gperf generates a perfect hash function from a key set.
component  : system.utils
description: |
    Gperf generates a perfect hash function from a key set.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
